version: "3.8"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: personal-vpn-container
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SERVERURL=${WIREGUARD_SERVERURL}
      - SERVERPORT=${WIREGUARD_SERVERPORT}
      - PEERS=${WIREGUARD_PEERS}
      - PEERDNS=${WIREGUARD_PEERDNS}
      - INTERNAL_SUBNET=${WIREGUARD_INTERNAL_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_ALLOWEDIPS}
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=true
    volumes:
      - ${DEPLOY_PATH}/personal/wireguard:/config
      - ${DEPLOY_PATH}/personal/modules:/lib/modules
    networks:
      - personal-network
    ports:
      - "${WIREGUARD_SERVERPORT}:${WIREGUARD_SERVERPORT}/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    restart: unless-stopped
    depends_on:
      - unbound

  unbound:
    container_name: personal-dns-container
    image: "mvance/unbound:latest"
    networks:
      - personal-network
    volumes:
      - ${DEPLOY_PATH}/personal/unbound/a-records.conf:/opt/unbound/etc/unbound/a-records.conf
    restart: unless-stopped

  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=${NEXTCLOUD_APACHE_PORT}
      - APACHE_ADDITIONAL_NETWORK=deploy_personal-network
      - APACHE_IP_BINDING=0.0.0.0
    ports:
      - "${NEXTCLOUD_PORT}:8080"
    networks:
      personal-network:
        ipv4_address: ${NEXTCLOUD_IPV4}
    depends_on:
      - caddy

  caddy:
    build:
      context: ./personal/caddy
      dockerfile: Dockerfile
    restart: always
    container_name: caddy
    volumes:
      - ${DEPLOY_PATH}/personal/caddy:/etc/caddy
      - ${DEPLOY_PATH}/personal/caddy/certs:/certs
      - ${DEPLOY_PATH}/personal/caddy/config:/config
      - ${DEPLOY_PATH}/personal/caddy/data:/data
      - ${DEPLOY_PATH}/personal/caddy/sites:/srv
    ports:
      - "80:80"
      - "443:443"
    networks:
      - personal-network
      - nextcloud-aio
    depends_on:
      - unbound

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${DEPLOY_PATH}/personal/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer

  redbot:
    container_name: redbot
    build:
      context: ./personal/redbot
      dockerfile: Dockerfile
      args:
        BOT_NAME: ${REDBOT_NAME}
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer

  vtt:
    container_name: vtt
    hostname: vtt
    build:
      context: ./personal/vtt
      dockerfile: Dockerfile
      args:
        FOUNDRY_USERNAME: ${FOUNDRY_USERNAME}
        FOUNDRY_PASSWORD: ${FOUNDRY_PASSWORD}
    volumes:
      - ${DEPLOY_PATH}/personal/vtt12/data:/root/.local/share
    networks:
      - personal-network

  homeserver:
    container_name: homeserver
    image: girlbossceo/conduwuit:main
    restart: unless-stopped
    volumes:
      - conduwuit_db:/var/lib/conduwuit
    networks:
      - personal-network
    environment:
      - CONDUWUIT_SERVER_NAME=${MATRIX_SERVER_NAME}
      - CONDUWUIT_DATABASE_PATH=/var/lib/conduwuit
      - CONDUWUIT_PORT=6167
      - CONDUWUIT_MAX_REQUEST_SIZE=20000000
      - CONDUWUIT_ALLOW_REGISTRATION=${MATRIX_ALLOW_REGISTRATION}
      - CONDUWUIT_REGISTRATION_TOKEN=${MATRIX_REGISTRATION_TOKEN}
      - CONDUWUIT_ALLOW_FEDERATION='true'
      - CONDUWUIT_ALLOW_CHECK_FOR_UPDATES='true'
      - CONDUWUIT_TRUSTED_SERVERS='["${MATRIX_SERVER_NAME}", "matrix.org"]'
      - CONDUWUIT_TURN_URIS='["turn:${MATRIX_SERVER_NAME}?transport=udp", "turn:${MATRIX_SERVER_NAME}?transport=tcp"]'
      - CONDUWUIT_ADDRESS=0.0.0.0
      - CONDUWUIT_URL_PREVIEW_DOMAIN_EXPLICIT_ALLOWLIST='["www.reddit.com", "www.youtube.com"]'
      - CONDUWUIT_ALLOW_LEGACY_MEDIA='true'
      - CONDUWUIT_NEW_USER_DISPLAYNAME_SUFFIX=''
    depends_on:
      - nextcloud-aio-mastercontainer

  element:
    container_name: element
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./personal/matrix/element-config.json:/app/config.json
    environment:
      - ELEMENT_WEB_PORT=3030
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer
      - homeserver

  turn:
    container_name: coturn-server
    image: docker.io/coturn/coturn
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./personal/matrix/coturn.conf:/etc/coturn/turnserver.conf

  cinny:
    container_name: cinny
    image: cinny:latest
    restart: unless-stopped
    volumes:
      - ./personal/matrix/elementcall/config.json:/app/element-call/dist/config.json
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer
      - homeserver

  mautrix-discord:
    container_name: mautrix-discord
    image: dock.mau.dev/mautrix/discord:4927a73ce7411f3970803d35c22f0c8c96dc2d7e-amd64
    restart: unless-stopped
    volumes:
      - ./personal/matrix/discord/data:/data
    networks:
      - personal-network
    depends_on:
      - database
      - homeserver

  database:
    image: 'postgres:latest'
    container_name: 'database'
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - personal-network
    depends_on:
      - homeserver
      - nextcloud-aio-mastercontainer

  mmr:
    image: 'docker.io/turt2live/matrix-media-repo:v1.3.8'
    container_name: 'mmr'
    volumes:
      - ./personal/matrix/mmr:/data
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer
      - homeserver
      - database

  element-call:
    image: 'ghcr.io/element-hq/element-call:sha-1702b15'
    container_name: element-call
    volumes:
      - ./personal/matrix/elementcall/config.json:/app/config.json
    networks:
      - personal-network
    depends_on:
      - nextcloud-aio-mastercontainer
      - homeserver
      - database

  livekit:
    image: livekit/livekit-server
    container_name: livekit
    command: --config /etc/livekit.yaml
    volumes:
      - ./personal/matrix/elementcall/livekit.yaml:/etc/livekit.yaml
    ports:
      - "50100-50200:50100-50200/udp"
    networks:
      - personal-network
    restart: unless-stopped

  livekit-jwt:
    container_name: livekit-jwt
    image: ghcr.io/element-hq/lk-jwt-service:0.2.3
    environment:
      - LIVEKIT_SECRET=${LIVEKIT_SECRET}
      - LIVEKIT_KEY=${LIVEKIT_KEY}
      - LIVEKIT_URL=https://${LIVEKIT_URL}/livekit/sfu
    networks:
      - personal-network
    restart: unless-stopped
  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    networks:
      - personal-network
    restart: always
    volumes:
     - ./gitea-new:/var/lib/gitea
     - ./gitea-config:/etc/gitea
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__server__START_SSH_SERVER=true
      - GITEA__server__SSH_PORT=22
      - GITEA__server__SSH_LISTEN_PORT=2222
      - GITEA__server__SSH_DOMAIN=gitea.${PRIMARY_DOMAIN}
    depends_on:
      - caddy
  cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: cloudflared
      networks:
        - personal-network
      restart: always
      volumes:
        - /etc/cloudflared:/etc/cloudflared:ro
        - /root/.cloudflared:/root/.cloudflared
      command: tunnel run filename.json
      environment:
        - TUNNEL_TOKEN=tokenhere=

networks:
  personal-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PERSONAL_IPAM_SUBNET}/24
  nextcloud-aio:
    name: nextcloud-aio_default
    external: true

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  conduwuit_db:
  gitea-data:
